services:
  - type: web
    name: staticBrowser
    env: node
    region: ohio  # Most reliable free tier region
    plan: free
    buildCommand: npm install --omit=dev --ignore-scripts=false
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: DISABLE_HEADLESS_WARNING
        value: "true"
      - key: PUPPETEER_TMP_DIR
        value: "/tmp/puppeteer"  # Optional: use in your Puppeteer launch config
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: staticBrowserSessions
    plan: free
    region: ohio
    ipAllowList: []
